--       T R I G G E R        --

-- TRIGGER AFTER PARA ACTUALIZAR LA DISPONIBILIDAD DE LAS HABITACION DESPUES DE QUE SE HIZO LA RESERVA --
DELIMITER //
CREATE TRIGGER actualizar_disponibilidad 
AFTER INSERT ON habitacion 
FOR EACH ROW 
BEGIN
UPDATE disponible
SET disponible = 0
WHERE idhabitacion = NEW.idhabitacion;
END// 
DELIMITER ; 




-- TRIGGER BEFORE PARA VERIFICAR LA DISPONIBILIDAD DE LA HABITACION ANTES DE REALIZAR UNA RESERVA -- 
DROP TRIGGER IF EXISTS verifica_disponibilidad;
DELIMITER // 
CREATE TRIGGER verifica_disponibilidad 
BEFORE INSERT ON HABITACION
FOR EACH ROW 
BEGIN 
DECLARE habitacion INT;
SELECT disponible INTO habitacion 
FROM habitacion
WHERE idhabitacion = NEW.idhabitacion;
IF disponible = O THEN 
SIGNAL SQLSTATE "45000"
SET MESSAGE_TEXT = "LA HABITACION SELECCIONADA NO ESTA DISPONIBLE";
END IF;
END //
DELIMITER ; 